server {
    listen 80;
    server_name cv.djro.fr;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name cv.djro.fr;

    ssl_certificate /etc/letsencrypt/live/cv.djro.fr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cv.djro.fr/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml image/svg+xml font/woff2;
    gzip_min_length 1000;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|woff2|webp|mp4)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
